version: '3.8'

services:
  backend:
    build: ./BACKEND
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./BACKEND/.env

  frontend:
    build: ./FRONTEND
    ports:
      - "3000:80"
    depends_on:
      - backend