# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - BACKEND-SUNU-SCHOOL-AI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sunuschooaiacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_199b207ed2ae4ef3bb1d11ccf66a43a6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_51aec85e9c4444b39d50d5b812319558 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sunuschooaiacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_199b207ed2ae4ef3bb1d11ccf66a43a6 }}/backend-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BACKEND-SUNU-SCHOOL-AI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_af739159f799477b95cb21150b4ce843 }}
        images: 'sunuschooaiacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_199b207ed2ae4ef3bb1d11ccf66a43a6 }}/backend-app:${{ github.sha }}'